name: Publish Python 🐍 distributions 📦 to PyPI and TestPyPI

on: 
  push:
    branches:
      - main
    paths:
      - 'setup.py'

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@main
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Build a distribution
      run: >-
        python setup.py sdist
    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.testpypi_token }}
        repository_url: https://test.pypi.org/legacy/

